vim.cmd("colorscheme onedark")
vim.cmd("filetype plugin indent on")
vim.cmd("command! -nargs=? -range=% Space2Tab call IndentConvert(<line1>,<line2>,0,<q-args>)")
vim.cmd("command! -nargs=? -range=% Tab2Space call IndentConvert(<line1>,<line2>,1,<q-args>)")
vim.cmd("command! -nargs=? -range=% RetabIndent call IndentConvert(<line1>,<line2>,&et,<q-args>)")
